apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: $(params.project)-flows
  namespace: int
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - test-flows
