---
# Source: base/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project-mqsc-configmap
data:
  default.mqsc: |
      ALTER QMGR CHLAUTH (DISABLED)
      DEFINE CHANNEL(TAPESTRY.ESB.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(REQUIRED) MCAUSER('mqm')
      ALTER QMGR CCSID(1208)
  config.mqsc: "ALTER QMGR MAXMSGL(104857600)\r\nDEFINE QLOCAL(ORDSTATUS.DEADLQ) DEFBIND(NOTFIXED)
    DEFPSIST(YES) MAXDEPTH(999999) MAXMSGL(104857600) BOQNAME('') REPLACE\r\nALTER QMGR
    DEADQ(ORDSTATUS.DEADLQ)\r\n\r\nDEFINE QLOCAL('QL.OUT.ELK.EVENTS.TRANSMISSION') BOQNAME('QL.OUT.ELK.EVENTS.TRANSMISSION.BOQ')
    USAGE(XMITQ) MAXDEPTH(999999) MAXMSGL(104857600) DEFPSIST(YES) REPLACE\r\nDEFINE
    QLOCAL('QL.OUT.ELK.EVENTS.TRANSMISSION.BOQ') MAXDEPTH(999999) MAXMSGL(104857600)
    DEFPSIST(YES) REPLACE\r\nDEFINE QREMOTE(QL.OUT.ELK.EVENTS) RNAME (QL.OUT.ELK.EVENTS)
    RQMNAME (ELKQMGR) XMITQ (QL.OUT.ELK.EVENTS.TRANSMISSION)\r\n\r\n\r\nDEFINE QLOCAL('SAF.LOG.IN.TRANSMISSION')
    BOQNAME('SAF.LOG.IN.TRANSMISSION.BOQ') USAGE(XMITQ) MAXDEPTH(999999) MAXMSGL(104857600)
    DEFPSIST(YES) REPLACE\r\nDEFINE QLOCAL('SAF.LOG.IN.TRANSMISSION.BOQ') MAXDEPTH(999999)
    MAXMSGL(104857600) DEFPSIST(YES) REPLACE\r\nDEFINE QREMOTE (SAF.LOG.IN) RNAME (SAF.LOG.IN)
    RQMNAME (GENERALQMGR) XMITQ (SAF.LOG.IN.TRANSMISSION)\r\n\r\nDEFINE QLOCAL(ATEST.QL.OUT.ELK.EVENTS)
    MAXDEPTH(999999) MAXMSGL(104857600) DEFPSIST(YES) REPLACE\r\n\r\nDEFINE TOPIC(ORDER_STATUS_TOPIC)
    TOPICSTR('$SYS/Broker/+/Monitoring/order-status/#')\r\nDEFINE SUB(SUB.ORDER_STATUS)
    TOPICOBJ(ORDER_STATUS_TOPIC) DEST(QL.OUT.ELK.EVENTS)\r\nDEFINE SUB(SUB.ORDER_STATUS_DUMMY)
    TOPICOBJ(ORDER_STATUS_TOPIC) DEST(ATEST.QL.OUT.ELK.EVENTS)\r\n\r\nDEFINE TOPIC(OMS_FRAUDSTATUS.UPDATES.ROW)
    TOPICSTR('OMS_FRAUDSTATUS.UPDATES.ROW')\r\nDEFINE QLOCAL('QL.IN.OMS.ESB.FORTER.ORDERUPDATES')
    MAXDEPTH(999999) MAXMSGL(104857600) DEFPSIST(YES) REPLACE\r\nDEFINE QLOCAL('QL.IN.OMS.ESB.SIGNIFYD.ORDERUPDATES')
    MAXDEPTH(999999) MAXMSGL(104857600) DEFPSIST(YES) REPLACE\r\n\r\nDEFINE QALIAS(QA.IN.OMS_FRAUDSTATUS.UPDATES.ROW)
    TARGET(OMS_FRAUDSTATUS.UPDATES.ROW) TARGTYPE(TOPIC) REPLACE\r\nDEFINE SUB('SUB.OMS_FRAUDSTATUS.UPDATES.ROW')
    TOPICOBJ('OMS_FRAUDSTATUS.UPDATES.ROW') DEST('QL.IN.OMS.ESB.FORTER.ORDERUPDATES')
    REPLACE\r\n\r\nDEFINE TOPIC(OMS_FRAUDSTATUS.UPDATES) TOPICSTR('OMS_FRAUDSTATUS.UPDATES')\r\nDEFINE
    QALIAS(QA.IN.OMS_FRAUDSTATUS.UPDATES) TARGET(OMS_FRAUDSTATUS.UPDATES) TARGTYPE(TOPIC)
    REPLACE\r\nDEFINE SUB('SUB.OMS_FRAUDSTATUS.UPDATES') TOPICOBJ('OMS_FRAUDSTATUS.UPDATES')
    DEST('QL.IN.OMS.ESB.FORTER.ORDERUPDATES') REPLACE\r\nDEFINE SUB('SUB.OMS_FRAUDSTATUS.UPDATES_SIGNIFYD')
    TOPICOBJ('OMS_FRAUDSTATUS.UPDATES') DEST('QL.IN.OMS.ESB.SIGNIFYD.ORDERUPDATES')
    REPLACE\r\n\r\nDEFINE QLOCAL(QL.IN.NARVAR_OMS.RETURNUPDATES.ROW) PUT(ENABLED) GET(ENABLED)
