bases:
  - ../../base
patches:
  - path: image.yaml
  - path: replica.yaml
  - path: config.yaml
  - path: version.yaml
  - path: node-affinity.yaml
  - path: open-telemetry.yaml
  - patch: |-
      - op: add
        path: /spec/version
        value: 12.0.12-r6
    target:
      kind: Configuration
resources: #Here configurations will be automatically added
  - qa_pol_test.yaml
  - server_conf_ocp.yaml
  - pol_test.yaml
