apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: $params.project-mq-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/TapestryESB/$params.repo-gitops.git
        revision: HEAD
        files:
        - path: "MQ-ROSA/**/qa_config.json"
  template:
    metadata:
      name: '{{microservice}}-{{env}}'
    spec:
  project: $params.project
      source:
        repoURL: https://github.com/TapestryESB/$params.repo-gitops.git
        targetRevision: HEAD
        path: "MQ-ROSA/{{folder}}/{{env}}/"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
