apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: $params.project-flows
  namespace: int
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationProduction
  version: 12.0.12-r6
