kind: ConfigMap
apiVersion: v1
metadata:
  name: $params.project-mqwebuserconfigmap
  namespace: int
data:
  mqwebuser.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
        <adminRestEnabled>true</adminRestEnabled>
        <featureManager>
            <feature>openidConnectClient-1.0</feature>
            <feature>appSecurity-2.0</feature>
            <feature>basicAuthenticationMQ-1.0</feature>
            <feature>mq-rest-admin</feature>
            <feature>mq-rest</feature>
        </featureManager>
        <enterpriseApplication id="com.ibm.mq.console">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="admins" access-id="group:integration/admin"/>
                    <group name="admins" access-id="group:integration/queuemanager-webadmin"/>
                    <group name="admins" access-id="group:integration/webadmin"/>
                </security-role>
                <security-role name="MQWebAdminRO">
                    <group name="readers" access-id="group:integration/queuemanager-webadminro"/>
                    <group name="readers" access-id="group:integration/webadminro"/>
                </security-role>
                <security-role name="MQWebUser">
                    <group name="users" access-id="group:integration/queuemanager-webuser"/>
                    <group name="users" access-id="group:integration/webuser"/>
                </security-role>
            </application-bnd>
        </enterpriseApplication>
        <enterpriseApplication id="com.ibm.mq.rest">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="MQWebAdminGroup" realm="defaultRealm"/>
                </security-role>
                <security-role name="MQWebUser">
                    <group name="MQWebAdminGroup" realm="defaultRealm"/>
                </security-role>
                <security-role name="MFTWebAdmin">
                    <group name="MQWebAdminGroup" realm="defaultRealm"/>
                </security-role>
            </application-bnd>
        </enterpriseApplication>
        <queueManager>
          <name>TESTQMGR</name>
          <restEnabled>true</restEnabled>
        </queueManager> 
        <basicRegistry id="basic" realm="defaultRealm">
          <user name="mqadmin" password="mqadmin"/>
          <group name="MQWebAdminGroup">
            <member name="mqadmin"/>
          </group>
        </basicRegistry> 
        <authFilter id="integrationKeycloak">
            <webApp id="com.ibm.mq.console" name="com.ibm.mq.console" matchType="equals"/>
        </authFilter>
        <openidConnectClient id="mqclient"
            authFilterRef="integrationKeycloak"
            disableLtpaCookie="true"
            jwtAccessTokenRemoteValidation="require"
            clientId="${mqOidcClientId}"
            clientSecret="${mqOidcClientSecret}"
            scope="openid profile"
            signatureAlgorithm="RS256"
            groupIdentifier="effective-roles"
            userIdentifier="preferred_username"
            realmName="integration"
            discoveryEndpointUrl="${env.MQ_OIDC_DISCOVERY_ENDPOINT_URL}">
        </openidConnectClient>
        <jndiEntry jndiName="icp4iPlatformServicesUrl" value="${env.MQ_CP4I_SERVICES_URL}/v1"/>
        <jndiEntry jndiName="integrationKeycloakUrl" value="${env.MQ_KEYCLOAK_ENDPOINT_URL}"/>
