---
# Source: base/templates/update.yaml
# Source: base/templates/qm-template.yaml
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $params.project-qmgr
  namespace: int
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    helm.sh/hook-weight: "300"
spec:
  annotations:
    productMetric: FREE
  license:
    accept: true
    
    license: L-JTPV-KYG8TF
    
    use: NonProduction
  queueManager:
    debug: false
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    logFormat: Basic
    metrics:
      enabled: true
    name: TESTQMGR
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 400m
        memory: 1024M
      requests:
        cpu: 200m
        memory: 256M
    route:
      enabled: true
    
    availability:
      type: NativeHA
    
    image: "407690150649.dkr.ecr.us-east-1.amazonaws.com/openshift-cicd-base-images:mq-9.4.0.0-r3"
    imagePullPolicy: Always
    storage:
      defaultClass: gp3-csi-ebs
      defaultDeleteClaim: true
      persistedData:
        class: gp3-csi-ebs
        deleteClaim: true
        enabled: true
        size: 2Gi
        type: persistent-claim
      queueManager:
        class: gp3-csi-ebs
        deleteClaim: true
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: true
    mqsc:
    - configMap:
        name: wms-mqsc-configmap
        items:
        - default.mqsc
        - config.mqsc
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - test-qmgr
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: qmgr
        env:
        - name: MQSNOAUT
          value: "yes"
        - name: LANG
          value: C.utf8
        - name: LC_ALL
          value: C.utf8
      imagePullSecrets: 
        - name: ecr-entitlement-key
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ""
  version: 9.4.0.0-r3
  telemetry:
     tracing:
       instana:
         enabled: true
         protocol: http
  web:
    enabled: true
  pki:
    keys:
      - name: certificate
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: qmgr-tls-secret
    trust:
      - name: ca
        secret:
          items:
            - tls.crt
          secretName: qmgr-tls-secret
