bases:
  - ../../base
patches:
  - path: image.yaml
  - path: replica.yaml
  - path: config.yaml
  - path: version.yaml
  - path: node-affinity.yaml
  - patch: |-
      - op: add
        path: /spec/version
        value: 12.0.12-r13
    target:
      kind: Configuration
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: pp
    target:
      kind: IntegrationRuntime
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: pp
    target:
      kind: Configuration
    target:
      kind: Configuration
resources: #Here configurations will be automatically added
  - pp_pol_test.yaml
  - server_conf_ocp.yaml
  - pol_test.yaml
