apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: $params.project-flows
  namespace: int
spec:
  configurations: 
    - ace-cp4i-keystore
    - ace-cp4i-keystore-dbparms

