apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: $(params.project)-flows
  namespace: int
spec:
  template:
    spec:
      containers:
        - name: runtime
          image: 407690150649.dkr.ecr.us-east-1.amazonaws.com/openshift-cicd:test-flows-qa-f6fd3dba58f9403bf49dadad8eb1285e84c30225
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 300Mi
          env:
            - name: CONFIG_COMMIT_ID
              value: "dcfcd5acd580b0a855a349a662a2e93a06"
            - name: LANG
              value: C.utf8
            - name: LC_ALL
              value: C.utf8
