resources:
  - configmap.yaml
  - qm-template.yaml
#  - route.yaml
commonAnnotations:
  configuration/mqsc-version: '3e295c9dd467d361c2c9ecee64a5fca623615e53'
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: pp
    target:
      kind: ConfigMap
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: pp
    target:
      kind: QueueManager
