apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: $(params.project)-ace-applicationset-pp
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/TapestryESB/$(params.repo)-gitops.git
        revision: HEAD
        files:
        - path: "ACE-ROSA/**/overlays/**/pp_config.json"
  template:
    metadata:
      name: '{{microservice}}-{{env}}'
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.tapestry: uasim@tapestry.com;nali@tapestry.com
    spec:
  project: $(params.project)
      source:
        repoURL: https://github.com/TapestryESB/$(params.repo)-gitops.git
        targetRevision: HEAD
        path: "ACE-ROSA/{{folder}}/overlays/{{env}}/"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      ignoreDifferences:
        - group: appconnect.ibm.com
          kind: IntegrationRuntime
          jsonPointers:
